= drawio-exporter

Drawio-exporter provides enhanced capabilities to the export feature of drawio-desktop.

== Features

* Recursive export
* Partial export (newer, or based on git reference)
* Additional export formats with link extraction

== Supported Export formats

* **draw.io** export formats: jpg, pdf, png, svg, vsdx, and xml
* **drawio-exporter** additional formats
** adoc - Export in PNG and create an additional asciidoc file (with support external links).
** md - Export in PNG and create an additional markdown file (with support external links).

== Installation

* Via https://doc.rust-lang.org/cargo/getting-started/installation.html[Cargo]
+
[source,shell]
----
cargo install drawio-exporter
----

* Build Manually
+
[source,shell]
----
git clone --depth 1 git@github.com:rlespinasse/drawio-exporter.git ~/.drawio-exporter
cd ~/.drawio-exporter
cargo install --path .
cargo build --release
# put the resulting `target/release/drawio-exporter` executable on your PATH.
----

== Used by

* Docker image https://github.com/rlespinasse/drawio-export[**rlespinasse/drawio-export**] which use the export capabilities of this tool,
** And GitHub Action https://github.com/rlespinasse/drawio-export-action[**rlespinasse/drawio-export-action**] which is build on top of **drawio-export** docker image.

== Contributing

Pull requests are welcome.
For major changes, please open an issue first to discuss what you would like to change.

Please make sure to update tests as appropriate.
