name: Build

on: push

env:
  RUSTFLAGS: '-Dwarnings'

permissions: read-all

concurrency:
  group: build-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Preflight // Test
        run: |
          sudo apt-get install -y xvfb libnotify4 libsecret-1-0
          wget -q https://github.com/jgraph/drawio-desktop/releases/download/v30.3.14/drawio-amd64-30.3.14.deb
          sudo dpkg -i drawio-amd64-30.3.14.deb
          sudo apt-get -y -f install

      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Cache
        uses: actions/cache@v6
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - uses: taiki-e/install-action@v2.86.4
        with:
          tool: just

      - name: Build
        run: just build

      - name: Test
        run: xvfb-run --auto-servernum just test

      - name: Format
        run: just fmt-check

      - name: Clippy
        run: just clippy

      - name: Audit
        run: |
          cargo install cargo-audit
          just audit
