name: Build

on: pull_request

env:
  RUSTFLAGS: '-Dwarnings'

permissions: read-all

concurrency:
  group: build-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Preflight // Test
        run: |
          sudo apt-get install -y xvfb libnotify4 libsecret-1-0
          wget -q https://github.com/jgraph/drawio-desktop/releases/download/v31.3.2/drawio-amd64-31.3.2.deb
          sudo dpkg -i drawio-amd64-31.3.2.deb
          sudo apt-get -y -f install

      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Cache
        uses: actions/cache@v6
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - uses: jdx/mise-action@c2a87611a18de5b3828c5652fe268e992400cb5c # v4.3.0

      - name: Build
        run: just build

      - name: Test
        run: xvfb-run --auto-servernum just test

      - name: Format
        run: just fmt-check

      - name: Clippy
        run: just clippy

      - name: Audit
        run: just audit
