name: Security audit

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    paths:
      - '**/Cargo.toml'
      - '**/Cargo.lock'

permissions: read-all

concurrency:
  group: security-audit-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  security-audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - uses: taiki-e/install-action@v2
        with:
          tool: just

      - name: Audit
        run: |
          cargo install cargo-audit
          just audit
